Capstone Project
deniodev/WEB-DEV-COURSE-EVENT pull request #3
Opened 2023-04-19 16:15 UTC by deniodev

2023-04-19 19:08 UTC, DuaneDave requested changes
Hi @deniodev 👋, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-19 19:08 UTC, DuaneDave commented on index.html
> +            </nav>
I strongly recommend that you reduce the margin on the right side of the navigation because its currently not very visually appealing and its not consistent with that of the left. Furthermore, i suggest that you follow better usage of semantic tags. Move the navigation outside of the `main` tag and wrap it with a header tag for better accessibility and semantic.

Your design

<img width="950" alt="navigation" src="https://user-images.githubusercontent.com/84930355/233166109-d291aca9-d548-40b6-b60a-ba68a4a15768.PNG">


Behance design
<img width="629" alt="navbar" src="https://user-images.githubusercontent.com/84930355/233166832-f4b9581a-9508-4d60-85d1-ef6538fc9e63.PNG">


NOTE: Pay attention to the dark color as your version is not the same with that on behance

2023-04-19 19:08 UTC, DuaneDave commented on index.html
> +        </div>
Please try to close the gap between the text and the underline in order to make it match the design on behance, this will make the design look nice well organized and in consistency across the page. Please review this in everyother header of the page both homepage and about page.

Your design
<img width="246" alt="header" src="https://user-images.githubusercontent.com/84930355/233170421-9bbdae7a-564c-4669-8748-ea06a2bda036.PNG">

Behance design
<img width="168" alt="look" src="https://user-images.githubusercontent.com/84930355/233170558-dc566344-9944-4f4b-8d59-967412b1ccbf.PNG">

2023-04-19 19:08 UTC, DuaneDave commented on index.html
> +                    <article>
The cards are expected to have a border when it is being hovered on. I recommend including this in your design to make the section more interactive.

Also, on the mobile view, the contents of the text are not centrally aligned and i suggest you review this in order to make the section correctly aligned.


<img width="841" alt="card" src="https://user-images.githubusercontent.com/84930355/233171678-a75a8cb7-2de2-4010-8104-96a305db7643.PNG">

on mobile
<img width="226" alt="bad" src="https://user-images.githubusercontent.com/84930355/233171821-bf722be5-d7c6-4798-acef-e1ec11b736e1.PNG">

2023-04-19 19:08 UTC, DuaneDave commented on index.html
> +        <div class="hello-container">
To follow best practices, I recommend making this tag and every `div` which is the wrapper of every section a `section` tag. This will add more structure to your code and improve the accessibility of your webpage.

2023-04-19 19:08 UTC, DuaneDave commented on main.js
> +    <img src=${item.image}>
TO make the images accessible, consider adding an alt text for them. This also will make something to show on the screen when a user has poor internet connection and not just a broken image.

2023-04-20 16:58 UTC, deniodev commented
Hi @DuaneDave 

Kindly see below the requested changes I did.

- [ ] Adjust the margins of the Nav bar;
- [ ] Change the HTML tags for better accessibility and sematic;
- [ ] Reduce the gap between the text and the underline;
- [ ] Add hover effects on programs cards;
- [ ] Align the text of programs cards on mobile view;
- [ ] Add an alt text for the images on students review section.

2023-04-20 17:12 UTC, iambenkis approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 17:12 UTC, iambenkis commented on README.md
> +
- [ ] [OPTIONAL] Good job implementing the changes asked by the previous reviewer, noticed that `Cindy Shin` is not an author of the project. Kindly make sure you update that 👍

2023-04-20 17:31 UTC, merged